import { useState, useEffect, useRef } from "react";
const ML=[{id:"claude-sonnet-4-6",l:"Sonnet 4.6"},{id:"claude-opus-4-6",l:"Opus 4.6"},{id:"claude-haiku-4-5",l:"Haiku 4.5"},{id:"gpt-4o",l:"GPT-4o"},{id:"gemini-2.5-pro",l:"Gemini 2.5 Pro"}];
const DK=[{id:"ceo",label:"CEO",icon:"🎯",c:"#6366f1",bio:"Strategy, sales, fundraising."},{id:"cto",label:"CTO",icon:"🧠",c:"#06b6d4",bio:"Architecture, ML, tech leadership."},{id:"back",label:"Backend",icon:"⚡",c:"#8b5cf6",bio:"APIs, distributed systems."},{id:"front",label:"Frontend",icon:"🎨",c:"#f59e0b",bio:"React, UI/UX, design systems."},{id:"mob",label:"Mobile",icon:"📱",c:"#3b82f6",bio:"iOS/Android development."},{id:"ml",label:"ML Eng",icon:"🤖",c:"#10b981",bio:"NLP, embeddings, eval."},{id:"ops",label:"DevOps",icon:"🛡",c:"#ef4444",bio:"K8s, CI/CD, security."},{id:"des",label:"Designer",icon:"✨",c:"#ec4899",bio:"Figma, prototyping."},{id:"mrk",label:"Marketer",icon:"📈",c:"#14b8a6",bio:"SEO, ads, growth."},{id:"wr",label:"Writer",icon:"✏️",c:"#a855f7",bio:"Content, docs."},{id:"pm",label:"PM",icon:"📋",c:"#f97316",bio:"Roadmap, priorities."},{id:"qa",label:"QA",icon:"🔍",c:"#84cc16",bio:"Testing, quality."}];
const PP=[{id:"m1",av:"👨‍💼"},{id:"m2",av:"👨‍💻"},{id:"m3",av:"🧑‍💼"},{id:"w1",av:"👩‍💼"},{id:"w2",av:"👩‍💻"},{id:"w3",av:"🧑‍💻"}];
const CH={general:{n:"General",i:"💬"},eng:{n:"Engineering",i:"⚙️"},prod:{n:"Product",i:"📊"},stand:{n:"Standup",i:"📋"}};
const KC5=["backlog","todo","in_progress","review","done"];
const KN={backlog:"Backlog",todo:"To Do",in_progress:"In Progress",review:"Review",done:"Done"};
const KK={backlog:"#64748b",todo:"#6366f1",in_progress:"#f59e0b",review:"#a855f7",done:"#10b981"};
const PP2={P0:"#ef4444",P1:"#f59e0b",P2:"#6366f1",P3:"#94a3b8"};
const ts=()=>{const d=new Date();return`${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`;};
const RM=[{id:"r1",ph:"Phase 1 — MVP",c:"#6366f1",s:0,d:3,it:["Core proxy","Classifier","Dashboard v1","5 beta"]},{id:"r2",ph:"Phase 2 — Beta",c:"#06b6d4",s:3,d:3,it:["ML classifier","Semantic cache","SDK v1","20 clients"]},{id:"r3",ph:"Phase 3 — Launch",c:"#10b981",s:6,d:3,it:["Model cascade","Analytics v2","Enterprise","100 clients"]},{id:"r4",ph:"Phase 4 — Scale",c:"#f59e0b",s:9,d:3,it:["Multi-region","Marketplace","Mobile","500 clients"]}];
const EC={m:["1","2","3","4","5","6","7","8","9","10","11","12"],r:[0,0,2,5,12,26,40,65,95,130,170,220],co:[35,35,38,40,42,45,50,55,60,65,70,78],u:[0,50,150,400,800,1500,2500,4000,6000,9000,13000,18000]};
const PS=[{t:"Проблема",i:"🔥",tx:"LLM API стоит дорого. 70% запросов не требуют мощных моделей."},{t:"Решение",i:"💡",tx:"Intelligent Routing — маршрутизация к оптимальному бэкенду."},{t:"Рынок",i:"📊",tx:"TAM $50B+ к 2030. AI agents CAGR 46%."},{t:"Продукт",i:"🚀",tx:"Classifier + Cache + Cascade. <30ms, 30-50% savings."},{t:"Бизнес",i:"💰",tx:"Usage-based. Free → Pro $49 → Team $149."},{t:"Traction",i:"📈",tx:"MVP ready. 5 beta. $26K MRR target."},{t:"Команда",i:"👥",tx:"AI-native team built with Sqwady."},{t:"Ask",i:"🎯",tx:"Pre-Seed $400K. 12 months runway."}];
const WK=[{t:"Architecture Overview",i:"🏗",tx:"Classifier → Cache → Cascade → Normalizer\nLatency: <30ms. SLA: 99.9%"},{t:"API Reference",i:"📖",tx:"POST /v1/route\n{prompt, model?, metadata?}\nOpenAI-compatible response"},{t:"Onboarding",i:"🚀",tx:"1. Sign up → API key\n2. pip install ir-sdk\n3. Replace openai.chat() → ir.chat()\n4. See savings"},{t:"Team Agreements",i:"🤝",tx:"Standup: daily 09:00\nSprint: 2 weeks\nDeploy: canary → full\nPR review: required"}];
const CSS=`@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500&display=swap');
:root{--bg:#09090b;--bg2:#18181b;--bg3:#27272a;--bg4:#3f3f46;--bd:#27272a;--bd2:#3f3f46;--t:#fafafa;--t2:#a1a1aa;--t3:#71717a;--ac:#818cf8;--ac2:#6366f1;--gn:#34d399}
*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Outfit',sans-serif;background:var(--bg);color:var(--t)}
::-webkit-scrollbar{width:5px}::-webkit-scrollbar-thumb{background:var(--bg4);border-radius:3px}
input,textarea,select{font-family:inherit}
@keyframes fu{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:none}}
@keyframes pop{0%{transform:scale(.85);opacity:0}100%{transform:scale(1);opacity:1}}
.fu{animation:fu .4s ease both}.pop{animation:pop .25s ease both}`;
function Bt({children,onClick,v="p",sm,dis,sx}){const s={border:"none",borderRadius:10,cursor:dis?"not-allowed":"pointer",fontWeight:600,fontFamily:"inherit",transition:"all .15s",display:"inline-flex",alignItems:"center",gap:6,opacity:dis?.5:1};const vs=v==="p"?{background:"var(--ac2)",color:"#fff",padding:sm?"6px 14px":"10px 20px",fontSize:sm?12:14}:{background:"transparent",color:"var(--t2)",padding:sm?"6px 14px":"10px 20px",fontSize:sm?12:14,border:"1px solid var(--bd2)"};return <button onClick={dis?undefined:onClick} style={{...s,...vs,...sx}}>{children}</button>;}

function Landing({onGo}){return (<div style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",overflow:"hidden",position:"relative"}}><div style={{position:"absolute",top:"-20%",left:"-10%",width:"60vw",height:"60vw",borderRadius:"50%",background:"radial-gradient(circle,rgba(99,102,241,0.07),transparent 70%)",pointerEvents:"none"}}/><div className="fu" style={{textAlign:"center",zIndex:1}}><div style={{fontSize:13,fontWeight:600,color:"var(--ac)",letterSpacing:2,textTransform:"uppercase",marginBottom:14}}>Welcome to</div><div style={{fontSize:64,fontWeight:900,letterSpacing:-3,background:"linear-gradient(135deg,#818cf8,#a78bfa,#c084fc)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",marginBottom:10}}>Sqwady</div><div style={{fontSize:17,color:"var(--t2)",maxWidth:460,lineHeight:1.6,marginBottom:32}}>Операционная система для AI-стартапа.<br/>Команда · Roadmap · Экономика · Питчи · Wiki</div><button onClick={onGo} style={{padding:"14px 44px",border:"none",borderRadius:14,cursor:"pointer",background:"linear-gradient(135deg,var(--ac2),#8b5cf6)",color:"#fff",fontSize:17,fontWeight:700,fontFamily:"inherit",boxShadow:"0 8px 32px rgba(99,102,241,0.3)"}}>Начать →</button></div></div>);}

function ProjSetup({onNext}){const[n,sN]=useState("");const[d,sD]=useState("");return (<div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div className="fu" style={{width:"100%",maxWidth:480,textAlign:"center"}}><div style={{fontSize:13,fontWeight:600,color:"var(--ac)",letterSpacing:2,textTransform:"uppercase",marginBottom:8}}>Шаг 1</div><div style={{fontSize:26,fontWeight:800,marginBottom:24}}>Опиши проект</div><div style={{display:"flex",flexDirection:"column",gap:12,textAlign:"left"}}><input value={n} onChange={e=>sN(e.target.value)} placeholder="Название" style={{width:"100%",padding:"12px 16px",background:"var(--bg2)",border:"2px solid var(--bd)",borderRadius:12,color:"var(--t)",fontSize:16,fontWeight:600,outline:"none"}} onFocus={e=>e.target.style.borderColor="var(--ac)"} onBlur={e=>e.target.style.borderColor="var(--bd)"}/><textarea value={d} onChange={e=>sD(e.target.value)} rows={3} placeholder="Описание, цели, сроки..." style={{width:"100%",padding:"12px 16px",background:"var(--bg2)",border:"2px solid var(--bd)",borderRadius:12,color:"var(--t)",fontSize:14,lineHeight:1.5,resize:"vertical",outline:"none"}} onFocus={e=>e.target.style.borderColor="var(--ac)"} onBlur={e=>e.target.style.borderColor="var(--bd)"}/></div><Bt onClick={()=>onNext({name:n||"My Project",desc:d})} dis={!n.trim()} sx={{marginTop:20,padding:"12px 36px"}}>Собрать команду →</Bt></div></div>);}
function OfficeBld({project,onDone}){
  const[pl,sPl]=useState([]);const[cfg,sCfg]=useState(null);const[ov,sOv]=useState(null);
  const add=(did,si)=>{if(pl.find(p=>p.slot===si))return;const d=DK.find(x=>x.id===did);if(d)sPl(p=>[...p,{...d,slot:si,per:null,pn:"",model:"claude-sonnet-4-6",bio:d.bio,mem:""}]);};
  const seat=(pid,si)=>{const p=PP.find(x=>x.id===pid);if(p){sPl(prev=>prev.map(x=>x.slot===si?{...x,per:p}:x));sCfg(si);}};
  const upd=(si,data)=>{sPl(p=>p.map(x=>x.slot===si?{...x,...data}:x));sCfg(null);};
  const rm=(si)=>sPl(p=>p.filter(x=>x.slot!==si));
  return (
    <div style={{minHeight:"100vh",display:"flex",flexDirection:"column",padding:14}}>
      <div style={{textAlign:"center",marginBottom:10}}><div style={{fontSize:13,fontWeight:600,color:"var(--ac)",letterSpacing:2,textTransform:"uppercase",marginBottom:4}}>Шаг 2</div><div style={{fontSize:22,fontWeight:800}}>Собери команду «{project.name}»</div><div style={{color:"var(--t2)",fontSize:11,marginTop:2}}>Перетащи стол → посади сотрудника → настрой</div></div>
      <div style={{display:"flex",flex:1,gap:10,overflow:"hidden"}}>
        <div style={{width:160,flexShrink:0,display:"flex",flexDirection:"column",gap:6,overflow:"auto"}}>
          <div style={{fontSize:10,fontWeight:700,color:"var(--t3)",textTransform:"uppercase"}}>🪑 Столы</div>
          {DK.map(d=>{const u=pl.find(p=>p.id===d.id);return (<div key={d.id} draggable={!u} onDragStart={e=>{e.dataTransfer.setData("tp","d");e.dataTransfer.setData("id",d.id);}} style={{padding:"5px 7px",background:u?"var(--bg3)":"var(--bg2)",border:"1px solid var(--bd)",borderRadius:6,cursor:u?"default":"grab",opacity:u?.3:1,display:"flex",alignItems:"center",gap:5}}><span style={{fontSize:14}}>{d.icon}</span><span style={{fontSize:10,fontWeight:600}}>{d.label}</span></div>);})}
          <div style={{fontSize:10,fontWeight:700,color:"var(--t3)",textTransform:"uppercase",marginTop:4}}>🧑 Люди</div>
          <div style={{display:"flex",flexWrap:"wrap",gap:4}}>{PP.map(p=>(<div key={p.id} draggable onDragStart={e=>{e.dataTransfer.setData("tp","p");e.dataTransfer.setData("id",p.id);}} style={{width:40,height:40,background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:7,cursor:"grab",display:"flex",alignItems:"center",justifyContent:"center",fontSize:18}}>{p.av}</div>))}</div>
        </div>
        <div style={{flex:1,background:"var(--bg2)",borderRadius:12,border:"1px solid var(--bd)",padding:14,position:"relative",overflow:"auto"}}>
          <div style={{position:"absolute",inset:0,opacity:.03,backgroundImage:"radial-gradient(circle,var(--t3) 1px,transparent 1px)",backgroundSize:"20px 20px",pointerEvents:"none"}}/>
          <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,position:"relative",zIndex:1}}>
            {Array.from({length:8},(_,i)=>{const e=pl.find(p=>p.slot===i);const o=ov===i;return (
              <div key={i} onDragOver={ev=>{ev.preventDefault();sOv(i);}} onDragLeave={()=>sOv(null)} onDrop={ev=>{ev.preventDefault();sOv(null);const tp=ev.dataTransfer.getData("tp"),id=ev.dataTransfer.getData("id");if(tp==="d")add(id,i);if(tp==="p"&&e&&!e.per)seat(id,i);}}
                style={{minHeight:100,borderRadius:10,border:`2px dashed ${o?"var(--ac)":e?e.c+"44":"var(--bd2)"}`,background:e?e.c+"08":o?"var(--ac)08":"var(--bg)",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",transition:"all .2s",position:"relative",padding:6}}>
                {!e&&<div style={{textAlign:"center",color:"var(--t3)"}}><div style={{fontSize:18}}>+</div><div style={{fontSize:8}}>Стол сюда</div></div>}
                {e&&<div className="pop" style={{textAlign:"center",width:"100%"}}><button onClick={()=>rm(i)} style={{position:"absolute",top:3,right:5,background:"none",border:"none",color:"var(--t3)",fontSize:10,cursor:"pointer"}}>✕</button><div style={{fontSize:22}}>{e.icon}</div><div style={{fontSize:9,fontWeight:700,color:e.c,marginBottom:3}}>{e.label}</div>
                  {!e.per?<div style={{fontSize:8,color:"var(--t3)",padding:3,border:"1px dashed var(--bd2)",borderRadius:5}}>↓ Посади</div>:<div onClick={()=>sCfg(i)} style={{cursor:"pointer"}}><div style={{fontSize:22}}>{e.per.av}</div><div style={{fontSize:8,color:"var(--t2)"}}>{e.pn||"⚙️"}</div></div>}</div>}
              </div>);})}
          </div>
        </div>
      </div>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:10}}><span style={{fontSize:11,color:"var(--t3)"}}>{pl.filter(p=>p.per).length} сотр · {pl.length} столов</span><Bt onClick={()=>onDone(pl.filter(p=>p.per))} dis={pl.filter(p=>p.per).length<1} sx={{padding:"10px 28px"}}>🚀 Запустить</Bt></div>
      {cfg!==null&&(()=>{const e=pl.find(p=>p.slot===cfg);if(!e)return null;return (<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.6)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:999}} onClick={()=>sCfg(null)}><div className="pop" style={{background:"var(--bg2)",borderRadius:14,padding:20,width:380,border:`1px solid ${e.c}33`}} onClick={ev=>ev.stopPropagation()}><CfgMod entry={e} onSave={d=>upd(cfg,d)} onClose={()=>sCfg(null)}/></div></div>);})()}
    </div>);
}
function CfgMod({entry:e,onSave,onClose}){const[n,sN]=useState(e.pn||"");const[b,sB]=useState(e.bio||"");const[m,sM]=useState(e.model);const[mm,sMM]=useState(e.mem||"");return (<><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:14}}><span style={{fontSize:28}}>{e.per?.av}</span><div style={{fontSize:14,fontWeight:700,color:e.c}}>{e.label}</div></div><div style={{display:"flex",flexDirection:"column",gap:8}}><input value={n} onChange={ev=>sN(ev.target.value)} placeholder="Имя" style={{width:"100%",padding:"8px 10px",background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:7,color:"var(--t)",fontSize:13,outline:"none"}}/><textarea value={b} onChange={ev=>sB(ev.target.value)} rows={2} style={{width:"100%",padding:"8px 10px",background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:7,color:"var(--t)",fontSize:12,outline:"none",resize:"vertical"}}/><select value={m} onChange={ev=>sM(ev.target.value)} style={{padding:"8px 10px",background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:7,color:"var(--t)",fontSize:12}}>{ML.map(md=><option key={md.id} value={md.id}>{md.l}</option>)}</select><input value={mm} onChange={ev=>sMM(ev.target.value)} placeholder="Memory URL" style={{width:"100%",padding:"8px 10px",background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:7,color:"var(--t)",fontSize:11,fontFamily:"'JetBrains Mono'",outline:"none"}}/></div><div style={{display:"flex",justifyContent:"flex-end",gap:6,marginTop:12}}><Bt onClick={onClose} v="g" sm>✕</Bt><Bt onClick={()=>onSave({pn:n,bio:b,model:m,mem:mm})} sm>✓</Bt></div></>);}
function RoadmapV(){const mo=["1","2","3","4","5","6","7","8","9","10","11","12"];return (<div style={{padding:16,overflow:"auto",height:"100%"}}><div style={{fontSize:16,fontWeight:700,marginBottom:14}}>🗺 Roadmap</div><div style={{position:"relative",minWidth:800}}><div style={{display:"flex",borderBottom:"1px solid var(--bd)",paddingBottom:6,marginBottom:12}}>{mo.map((m,i)=><div key={i} style={{flex:1,textAlign:"center",fontSize:9,color:"var(--t3)",fontWeight:600}}>Мес {m}</div>)}</div>{RM.map(r=>(<div key={r.id} style={{marginBottom:12}}><div style={{display:"flex",alignItems:"center",height:48}}><div style={{position:"absolute",left:`${(r.s/12)*100}%`,width:`${(r.d/12)*100}%`,height:42,background:`${r.c}18`,border:`2px solid ${r.c}44`,borderRadius:10,display:"flex",alignItems:"center",padding:"0 14px",cursor:"pointer"}} onMouseEnter={e=>{e.currentTarget.style.borderColor=r.c;}} onMouseLeave={e=>{e.currentTarget.style.borderColor=r.c+"44";}}><div><div style={{fontSize:12,fontWeight:700,color:r.c}}>{r.ph}</div><div style={{fontSize:9,color:"var(--t2)",marginTop:1}}>{r.it.join(" · ")}</div></div></div></div></div>))}<div style={{display:"flex",position:"absolute",top:0,bottom:0,left:0,right:0,pointerEvents:"none"}}>{mo.map((_,i)=><div key={i} style={{flex:1,borderRight:i<11?"1px solid var(--bd)":"none"}}/>)}</div></div></div>);}

function EconV(){const mx=Math.max(...EC.r,...EC.co);const be=EC.m.findIndex((_,i)=>EC.r[i]>=EC.co[i]);return (<div style={{padding:16,overflow:"auto",height:"100%"}}><div style={{fontSize:16,fontWeight:700,marginBottom:10}}>💰 Экономика</div><div style={{display:"flex",gap:8,marginBottom:16}}>{[{l:"ARR Y1",v:`$${EC.r.reduce((a,b)=>a+b,0)}K`,cl:"var(--gn)"},{l:"Costs",v:`$${EC.co.reduce((a,b)=>a+b,0)}K`,cl:"var(--ac)"},{l:"Break-even",v:be>=0?`Мес ${be+1}`:"—",cl:"#f59e0b"},{l:"Users M12",v:EC.u[11].toLocaleString(),cl:"#a855f7"}].map((m,i)=>(<div key={i} style={{flex:1,padding:12,background:"var(--bg2)",borderRadius:10,border:"1px solid var(--bd)"}}><div style={{fontSize:9,color:"var(--t3)",fontWeight:600,marginBottom:3}}>{m.l}</div><div style={{fontSize:20,fontWeight:800,color:m.cl}}>{m.v}</div></div>))}</div><div style={{fontSize:12,fontWeight:700,marginBottom:8}}>Revenue vs Costs ($K)</div><div style={{display:"flex",alignItems:"flex-end",gap:3,height:140,borderBottom:"1px solid var(--bd)",marginBottom:4}}>{EC.m.map((_,i)=>(<div key={i} style={{flex:1,display:"flex",gap:1,alignItems:"flex-end",height:"100%"}}><div style={{flex:1,background:"var(--gn)",borderRadius:"3px 3px 0 0",height:`${Math.max(2,(EC.r[i]/mx)*100)}%`,opacity:.8}}/><div style={{flex:1,background:"var(--ac)",borderRadius:"3px 3px 0 0",height:`${Math.max(2,(EC.co[i]/mx)*100)}%`,opacity:.8}}/></div>))}</div><div style={{display:"flex",gap:3,marginBottom:14}}>{EC.m.map((m,i)=><div key={i} style={{flex:1,textAlign:"center",fontSize:8,color:"var(--t3)"}}>{m}</div>)}</div><div style={{display:"flex",gap:10,fontSize:10,color:"var(--t2)"}}><span>🟢 Revenue</span><span>🔵 Costs</span></div></div>);}

function CalV({tasks,team}){const tm={};team.forEach(m=>{tm[m.id+m.slot]=m;});const now=new Date();const y=now.getFullYear(),mo=now.getMonth();const fd=new Date(y,mo,1).getDay();const dim=new Date(y,mo+1,0).getDate();const mn=["Янв","Фев","Мар","Апр","Май","Июн","Июл","Авг","Сен","Окт","Ноя","Дек"][mo];const cells=[];for(let i=0;i<(fd===0?6:fd-1);i++)cells.push(null);for(let d=1;d<=dim;d++)cells.push(d);const td=now.getDate();return (<div style={{padding:16,overflow:"auto",height:"100%"}}><div style={{fontSize:16,fontWeight:700,marginBottom:12}}>📅 {mn} {y}</div><div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:3}}>{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(d=><div key={d} style={{textAlign:"center",fontSize:10,fontWeight:700,color:"var(--t3)",padding:4}}>{d}</div>)}{cells.map((d,i)=>{const iT=d===td;const dt=d?tasks.filter((_,ti)=>((d+ti)%7===0||(d+ti)%5===0)).slice(0,2):[];return (<div key={i} style={{minHeight:60,padding:4,background:d?"var(--bg2)":"transparent",borderRadius:6,border:iT?"1px solid var(--ac)":"1px solid var(--bd)",opacity:d?1:.2}}>{d&&<><div style={{fontSize:11,fontWeight:iT?700:500,color:iT?"var(--ac)":"var(--t)",marginBottom:2}}>{d}</div>{dt.map(t=>(<div key={t.id} style={{fontSize:8,padding:"1px 3px",background:PP2[t.priority]+"18",borderRadius:3,color:PP2[t.priority],marginBottom:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",fontWeight:600}}>{t.title}</div>))}</>}</div>);})}</div></div>);}
function PitchV(){const[ac,sAc]=useState(0);const[sl,sSl]=useState(PS.map((s,i)=>({...s,id:i})));const[ed,sEd]=useState(false);return (<div style={{display:"flex",height:"100%",overflow:"hidden"}}><div style={{width:160,borderRight:"1px solid var(--bd)",padding:10,overflow:"auto"}}><div style={{fontSize:10,fontWeight:700,color:"var(--t3)",textTransform:"uppercase",letterSpacing:1,marginBottom:8}}>Слайды</div>{sl.map((s,i)=>(<div key={i} onClick={()=>{sAc(i);sEd(false);}} style={{padding:"6px 8px",borderRadius:6,cursor:"pointer",marginBottom:3,background:ac===i?"var(--ac2)":"transparent",color:ac===i?"#fff":"var(--t2)",fontSize:11,fontWeight:ac===i?700:500}}>{s.i} {s.t}</div>))}<Bt onClick={()=>{sSl(p=>[...p,{t:"New",i:"📄",tx:"",id:p.length}]);sAc(sl.length);}} sm sx={{marginTop:6,width:"100%",justifyContent:"center"}}>+ Слайд</Bt></div><div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",padding:24}}><div style={{width:"100%",maxWidth:580,aspectRatio:"16/9",background:"var(--bg2)",borderRadius:18,border:"2px solid var(--bd)",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:32,position:"relative"}}><div style={{position:"absolute",top:10,right:14}}><button onClick={()=>sEd(!ed)} style={{background:"var(--bg3)",border:"none",borderRadius:5,padding:"3px 8px",color:"var(--t2)",fontSize:10,cursor:"pointer"}}>{ed?"👁":"✏️"}</button></div>{ed?(<div style={{width:"100%",display:"flex",flexDirection:"column",gap:8}}><input value={sl[ac]?.t||""} onChange={e=>{const n=[...sl];n[ac]={...n[ac],t:e.target.value};sSl(n);}} style={{fontSize:20,fontWeight:800,background:"transparent",border:"none",borderBottom:"2px solid var(--bd)",color:"var(--t)",textAlign:"center",padding:6,outline:"none"}}/><textarea value={sl[ac]?.tx||""} onChange={e=>{const n=[...sl];n[ac]={...n[ac],tx:e.target.value};sSl(n);}} rows={4} style={{fontSize:13,background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:6,color:"var(--t2)",padding:10,lineHeight:1.5,outline:"none",resize:"vertical"}}/></div>):(<><div style={{fontSize:40,marginBottom:12}}>{sl[ac]?.i}</div><div style={{fontSize:24,fontWeight:800,marginBottom:10}}>{sl[ac]?.t}</div><div style={{fontSize:14,color:"var(--t2)",lineHeight:1.6,textAlign:"center",whiteSpace:"pre-wrap"}}>{sl[ac]?.tx}</div></>)}<div style={{position:"absolute",bottom:10,display:"flex",gap:3}}>{sl.map((_,i)=><div key={i} onClick={()=>sAc(i)} style={{width:i===ac?16:6,height:6,borderRadius:3,background:i===ac?"var(--ac2)":"var(--bg4)",cursor:"pointer",transition:"all .2s"}}/>)}</div></div></div></div>);}

function WikiV(){const[ac,sAc]=useState(0);const[pg,sPg]=useState(WK.map((w,i)=>({...w,id:i})));const[ed,sEd]=useState(false);return (<div style={{display:"flex",height:"100%",overflow:"hidden"}}><div style={{width:180,borderRight:"1px solid var(--bd)",padding:10,overflow:"auto"}}><div style={{fontSize:10,fontWeight:700,color:"var(--t3)",textTransform:"uppercase",letterSpacing:1,marginBottom:8}}>📚 Wiki</div>{pg.map((p,i)=>(<div key={i} onClick={()=>{sAc(i);sEd(false);}} style={{padding:"6px 8px",borderRadius:6,cursor:"pointer",marginBottom:3,background:ac===i?"var(--bg3)":"transparent",fontSize:11,fontWeight:ac===i?700:500,color:ac===i?"var(--t)":"var(--t2)"}}>{p.i} {p.t}</div>))}<Bt onClick={()=>{sPg(p=>[...p,{t:"New Page",i:"📄",tx:"",id:p.length}]);sAc(pg.length);sEd(true);}} sm sx={{marginTop:6,width:"100%",justifyContent:"center"}}>+ Страница</Bt></div><div style={{flex:1,padding:20,overflow:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}>{ed?<input value={pg[ac]?.t||""} onChange={e=>{const n=[...pg];n[ac]={...n[ac],t:e.target.value};sPg(n);}} style={{fontSize:20,fontWeight:800,background:"transparent",border:"none",borderBottom:"2px solid var(--bd)",color:"var(--t)",padding:4,outline:"none",flex:1}}/>:<div style={{fontSize:20,fontWeight:800}}>{pg[ac]?.i} {pg[ac]?.t}</div>}<button onClick={()=>sEd(!ed)} style={{background:"var(--bg3)",border:"none",borderRadius:5,padding:"4px 10px",color:"var(--t2)",fontSize:11,cursor:"pointer",marginLeft:8}}>{ed?"💾 Save":"✏️ Edit"}</button></div>{ed?<textarea value={pg[ac]?.tx||""} onChange={e=>{const n=[...pg];n[ac]={...n[ac],tx:e.target.value};sPg(n);}} style={{width:"100%",minHeight:300,padding:14,background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:10,color:"var(--t)",fontSize:13,lineHeight:1.7,fontFamily:"'JetBrains Mono'",outline:"none",resize:"vertical"}}/>:<div style={{fontSize:14,color:"var(--t2)",lineHeight:1.8,whiteSpace:"pre-wrap",fontFamily:"'JetBrains Mono'",background:"var(--bg2)",padding:16,borderRadius:10,border:"1px solid var(--bd)"}}>{pg[ac]?.tx}</div>}</div></div>);}
function WS({project,team}){
  const[vw,sVw]=useState("chat");const[ch,sCh]=useState("general");
  const[msgs,sMsgs]=useState(()=>{const o={};Object.keys(CH).forEach(k=>{o[k]=[];});if(team[0])o.general.push({id:1,f:team[0].id+team[0].slot,tx:`Команда ${project.name} собрана! Я ${team[0].pn||team[0].label}. Определяю приоритеты.`,t:"09:00"});if(team[1])o.general.push({id:2,f:team[1].id+team[1].slot,tx:"Начинаю архитектурный обзор.",t:"09:05"});if(team[2])o.general.push({id:3,f:team[2].id+team[2].slot,tx:"Инфраструктура готова. Жду задачи.",t:"09:10"});team.forEach((m,i)=>{o.stand.push({id:10+i,f:m.id+m.slot,tx:`Standup:\n✅ Онбординг\n🔄 Основные задачи\n🚫 Нет блокеров`,t:`09:${String(i*2).padStart(2,"0")}`});});return o;});
  const[tasks,sTasks]=useState(()=>team.map((m,i)=>({id:`T-${String(i+1).padStart(3,"0")}`,title:`Setup: ${m.pn||m.label}`,as:m.id+m.slot,pr:i<2?"P0":"P1",col:"todo",tags:["setup"]})));
  const[inp,sInp]=useState("");const[mod,sMod]=useState(null);const[isN,sIsN]=useState(false);const[flt,sFlt]=useState("all");
  const endR=useRef(null);const tm={};team.forEach(m=>{tm[m.id+m.slot]=m;});
  useEffect(()=>{endR.current?.scrollIntoView({behavior:"smooth"});},[ch,msgs]);
  const send=()=>{if(!inp.trim())return;const mx=inp.match(/^\/task\s+(.+)/);const m={id:Date.now(),f:"you",tx:inp,t:ts()};if(mx){const t={id:`T-${String(tasks.length+1).padStart(3,"0")}`,title:mx[1],as:team[0]?team[0].id+team[0].slot:"",pr:"P1",col:"todo",tags:["chat"]};sTasks(p=>[...p,t]);m.task=t.id+": "+mx[1];}sMsgs(p=>({...p,[ch]:[...(p[ch]||[]),m]}));sInp("");};
  const mv=(tid,col)=>sTasks(p=>p.map(t=>t.id===tid?{...t,col}:t));
  const svT=f=>{if(isN)sTasks(p=>[...p,{...f,id:`T-${String(p.length+1).padStart(3,"0")}`}]);else sTasks(p=>p.map(t=>t.id===f.id?f:t));sMod(null);sIsN(false);};
  const ft=flt==="all"?tasks:tasks.filter(t=>t.as===flt);
  const cm=msgs[ch]||[];
  const TABS=[{id:"chat",l:"💬 Чаты"},{id:"kanban",l:"📋 Kanban"},{id:"road",l:"🗺 Roadmap"},{id:"econ",l:"💰 Экономика"},{id:"cal",l:"📅 Календарь"},{id:"pitch",l:"🎤 Pitch"},{id:"wiki",l:"📚 Wiki"}];
  return (
    <div style={{height:"100vh",display:"flex",flexDirection:"column"}}>
      <div style={{height:44,background:"var(--bg2)",borderBottom:"1px solid var(--bd)",display:"flex",alignItems:"center",padding:"0 12px",justifyContent:"space-between",flexShrink:0}}>
        <div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:15,fontWeight:900,background:"linear-gradient(135deg,#818cf8,#a78bfa)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>Sqwady</span><span style={{fontSize:10,color:"var(--t3)",padding:"1px 6px",background:"var(--bg3)",borderRadius:4}}>{project.name}</span></div>
        <div style={{display:"flex",gap:1,background:"var(--bg3)",borderRadius:7,padding:2,overflow:"auto"}}>{TABS.map(v=>(<button key={v.id} onClick={()=>sVw(v.id)} style={{padding:"4px 10px",border:"none",borderRadius:5,cursor:"pointer",fontFamily:"inherit",background:vw===v.id?"var(--ac2)":"transparent",color:vw===v.id?"#fff":"var(--t3)",fontSize:10,fontWeight:600,whiteSpace:"nowrap"}}>{v.l}</button>))}</div>
        <span style={{fontSize:10,color:"var(--t3)"}}>{team.length} чел</span>
      </div>
      <div style={{flex:1,display:"flex",overflow:"hidden"}}>
        {vw==="road"&&<RoadmapV/>}
        {vw==="econ"&&<EconV/>}
        {vw==="cal"&&<CalV tasks={tasks} team={team}/>}
        {vw==="pitch"&&<PitchV/>}
        {vw==="wiki"&&<WikiV/>}
        {vw==="chat"&&(<>
          <div style={{width:180,background:"var(--bg2)",borderRight:"1px solid var(--bd)",display:"flex",flexDirection:"column",flexShrink:0,overflow:"auto"}}>
            <div style={{padding:"8px 8px 3px",fontSize:9,fontWeight:700,color:"var(--t3)",textTransform:"uppercase"}}>Чаты</div>
            {Object.entries(CH).map(([k,c])=>(<div key={k} onClick={()=>sCh(k)} style={{padding:"5px 8px",cursor:"pointer",background:ch===k?"var(--bg3)":"transparent",borderLeft:ch===k?"2px solid var(--ac)":"2px solid transparent"}}><span style={{fontSize:11,fontWeight:ch===k?700:500,color:ch===k?"var(--t)":"var(--t2)"}}>{c.i} {c.n}</span></div>))}
            <div style={{marginTop:"auto",borderTop:"1px solid var(--bd)",padding:6}}><div style={{fontSize:9,fontWeight:700,color:"var(--t3)",marginBottom:3}}>КОМАНДА</div>{team.map(m=>(<div key={m.id+m.slot} style={{display:"flex",alignItems:"center",gap:4,padding:"2px 0"}}><span style={{fontSize:14}}>{m.per?.av||m.icon}</span><span style={{fontSize:9,fontWeight:600,color:"var(--t)"}}>{m.pn||m.label}</span></div>))}</div>
          </div>
          <div style={{flex:1,display:"flex",flexDirection:"column"}}>
            <div style={{padding:"6px 12px",borderBottom:"1px solid var(--bd)"}}><span style={{fontSize:12,fontWeight:700}}>{CH[ch]?.i} {CH[ch]?.n}</span></div>
            <div style={{flex:1,overflowY:"auto",padding:"4px 0"}}>{cm.map(m=>{const d=m.f==="you"?{pn:"You",icon:"👤",c:"var(--ac)",per:{av:"👤"}}:tm[m.f]||{pn:"?",icon:"?",c:"#666",per:{av:"?"}};return (<div key={m.id} style={{display:"flex",gap:6,padding:"4px 12px"}}><span style={{fontSize:18,flexShrink:0}}>{m.f==="you"?"👤":d.per?.av||d.icon}</span><div style={{flex:1,minWidth:0}}><div style={{display:"flex",alignItems:"baseline",gap:4}}><span style={{fontWeight:700,fontSize:11,color:d.c}}>{d.pn||d.label}</span><span style={{fontSize:9,color:"var(--t3)",marginLeft:"auto"}}>{m.t}</span></div><div style={{fontSize:11,color:"var(--t2)",lineHeight:1.5,marginTop:1,whiteSpace:"pre-wrap"}}>{m.tx}</div>{m.task&&<div style={{marginTop:3,padding:"2px 6px",background:"var(--ac)11",borderRadius:4,fontSize:10,color:"var(--ac)"}}>📋 {m.task}</div>}</div></div>);})}<div ref={endR}/></div>
            <div style={{padding:"6px 10px",borderTop:"1px solid var(--bd)",background:"var(--bg2)"}}><div style={{fontSize:8,color:"var(--t3)",marginBottom:3,fontFamily:"'JetBrains Mono'"}}>/task Название</div><div style={{display:"flex",gap:4}}><input value={inp} onChange={e=>sInp(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Сообщение..." style={{flex:1,padding:"6px 10px",background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:7,color:"var(--t)",fontSize:12,outline:"none"}} onFocus={e=>e.target.style.borderColor="var(--ac)"} onBlur={e=>e.target.style.borderColor="var(--bd)"}/><Bt onClick={send} sm>→</Bt></div></div>
          </div></>)}
        {vw==="kanban"&&(<div style={{flex:1,display:"flex",flexDirection:"column",padding:12,overflow:"hidden"}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><span style={{fontSize:14,fontWeight:700}}>Kanban</span><div style={{display:"flex",gap:4}}><select value={flt} onChange={e=>sFlt(e.target.value)} style={{padding:"4px 6px",background:"var(--bg2)",border:"1px solid var(--bd)",borderRadius:5,color:"var(--t)",fontSize:10}}><option value="all">Все</option>{team.map(m=><option key={m.id+m.slot} value={m.id+m.slot}>{m.icon} {m.pn||m.label}</option>)}</select><Bt onClick={()=>{sIsN(true);sMod({title:"",as:team[0]?team[0].id+team[0].slot:"",pr:"P1",col:"todo",tags:[]});}} sm>+</Bt></div></div>
          <div style={{flex:1,display:"flex",gap:6,overflowX:"auto"}}>{KC5.map(c=>{const ct=ft.filter(t=>t.col===c);return (<div key={c} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();mv(e.dataTransfer.getData("tid"),c);}} style={{flex:"1 1 0",minWidth:150,background:"var(--bg2)",borderRadius:8,padding:8,display:"flex",flexDirection:"column",border:"1px solid var(--bd)"}}><div style={{display:"flex",alignItems:"center",gap:4,marginBottom:6}}><div style={{width:6,height:6,borderRadius:"50%",background:KK[c]}}/><span style={{fontSize:9,fontWeight:700,color:"var(--t2)",textTransform:"uppercase"}}>{KN[c]}</span><span style={{fontSize:8,color:"var(--t3)",marginLeft:"auto"}}>{ct.length}</span></div><div style={{flex:1,overflowY:"auto"}}>{ct.map(t=>(<div key={t.id} draggable onDragStart={e=>e.dataTransfer.setData("tid",t.id)} onClick={()=>{sIsN(false);sMod(t);}} style={{background:"var(--bg)",borderRadius:6,padding:"6px 8px",marginBottom:4,border:"1px solid var(--bd)",cursor:"grab",borderLeft:`3px solid ${PP2[t.pr]}`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:2}}><span style={{fontSize:8,fontFamily:"'JetBrains Mono'",color:"var(--t3)"}}>{t.id}</span><span style={{fontSize:8,fontWeight:700,color:PP2[t.pr]}}>{t.pr}</span></div><div style={{fontSize:10,fontWeight:600,marginBottom:3}}>{t.title}</div>{tm[t.as]&&<span style={{fontSize:12}}>{tm[t.as].per?.av||tm[t.as].icon}</span>}</div>))}</div></div>);})}</div>
        </div>)}
      </div>
      {mod&&(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.5)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:999}} onClick={()=>{sMod(null);sIsN(false);}}><div style={{background:"var(--bg2)",borderRadius:12,padding:18,width:360,border:"1px solid var(--bd)"}} onClick={e=>e.stopPropagation()}><div style={{fontSize:14,fontWeight:700,marginBottom:10}}>{isN?"➕ Новая":"✏️ "+mod.id}</div><input value={mod.title} onChange={e=>sMod({...mod,title:e.target.value})} placeholder="Название" style={{width:"100%",padding:"7px 10px",background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:6,color:"var(--t)",fontSize:13,outline:"none",marginBottom:6}}/><div style={{display:"flex",gap:6,marginBottom:6}}><select value={mod.as} onChange={e=>sMod({...mod,as:e.target.value})} style={{flex:1,padding:6,background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:6,color:"var(--t)",fontSize:11}}>{team.map(m=><option key={m.id+m.slot} value={m.id+m.slot}>{m.icon} {m.pn||m.label}</option>)}</select><select value={mod.pr} onChange={e=>sMod({...mod,pr:e.target.value})} style={{width:70,padding:6,background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:6,color:"var(--t)",fontSize:11}}>{Object.keys(PP2).map(p=><option key={p} value={p}>{p}</option>)}</select></div><select value={mod.col} onChange={e=>sMod({...mod,col:e.target.value})} style={{width:"100%",padding:6,background:"var(--bg)",border:"1px solid var(--bd)",borderRadius:6,color:"var(--t)",fontSize:11,marginBottom:10}}>{KC5.map(c=><option key={c} value={c}>{KN[c]}</option>)}</select><div style={{display:"flex",justifyContent:"flex-end",gap:6}}><Bt onClick={()=>{sMod(null);sIsN(false);}} v="g" sm>✕</Bt><Bt onClick={()=>svT(mod)} sm>✓</Bt></div></div></div>)}
    </div>);
}

export default function App(){const[pg,sPg]=useState("land");const[pj,sPj]=useState(null);const[tm,sTm]=useState(null);return (<><style>{CSS}</style>{pg==="land"&&<Landing onGo={()=>sPg("proj")}/>}{pg==="proj"&&<ProjSetup onNext={p=>{sPj(p);sPg("office");}}/>}{pg==="office"&&pj&&<OfficeBld project={pj} onDone={t=>{sTm(t);sPg("ws");}}/>}{pg==="ws"&&pj&&tm&&<WS project={pj} team={tm}/>}</>);}
